# Generated by rust2rpm 13
%bcond_without check

%global crate cbindgen

Name:		rust-%{crate}
Version:	0.15.0
Release:	1
Summary:	Tool for generating C bindings to Rust code

# Upstream license specification: MPL-2.0
License:	MPLv2.0
URL:		https://crates.io/crates/cbindgen
Source:		%{crates_source}

ExclusiveArch:	%{rust_arches}
%if %{__cargo_skip_build}
BuildArch:	noarch
%endif

BuildRequires:	rust-packaging

%global _description %{expand:
Tool for generating C bindings to Rust code.}

%description %{_description}

%if ! %{__cargo_skip_build}
%package -n %{crate}
Summary:	%{summary}

%description -n %{crate} %{_description}

%files -n %{crate}
%license LICENSE
%doc docs.md README.md
%{_bindir}/cbindgen
%endif

%package devel
Summary:	%{summary}
BuildArch:	noarch

%description devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files devel
%license LICENSE
%doc contributing.md docs.md internals.md README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package -n %{name}+default-devel
Summary:	%{summary}
BuildArch:	noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package -n %{name}+clap-devel
Summary:	%{summary}
BuildArch:	noarch

%description -n %{name}+clap-devel %{_description}

This package contains library source intended for building other packages
which use "clap" feature of "%{crate}" crate.

%files -n %{name}+clap-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires
%if %{with check}
echo %{__cxx}
echo %{__cc}
%endif

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif
